In [71]:
import pandas as pd

In [72]:
df=pd.read_csv(r"spam.csv")

In [73]:
df.head()

  label                                                sms
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [74]:
df["label"].replace({"ham":1,"spam":0},inplace=True)

C:\Users\hamzz\AppData\Local\Temp\ipykernel_7784\3592572936.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["label"].replace({"ham":1,"spam":0},inplace=True)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: label, Length: 5572, dtype: object

In [75]:
df

     label                                                sms
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [76]:
df.shape

(5572, 2)

In [77]:
df.drop_duplicates(inplace=True)

In [78]:
df.shape

(5169, 2)

In [79]:
df.isnull().sum()

label    0
sms      0
dtype: int64

# Using CountVectorizer class to split each word and treat them separately

In [80]:
from sklearn.feature_extraction.text import CountVectorizer

In [81]:
cv=CountVectorizer( max_features=500,   # only top 500 words
    min_df=10)

In [82]:
y=df["label"]
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5169, dtype: str

In [83]:
y.value_counts().unique()

array([4516,  653])

In [84]:
x=df["sms"]
x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: sms, Length: 5169, dtype: str

In [85]:
x=cv.fit_transform(x)

In [86]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 46830 stored elements and shape (5169, 500)>
  Coords	Values
  (0, 159)	1
  (0, 433)	1
  (0, 305)	1
  (0, 207)	1
  (0, 167)	1
  (0, 480)	1
  (0, 403)	1
  (0, 166)	1
  (0, 451)	1
  (1, 299)	1
  (1, 221)	1
  (1, 468)	1
  (2, 207)	1
  (2, 148)	1
  (2, 417)	3
  (2, 470)	1
  (2, 254)	1
  (2, 392)	1
  (2, 342)	1
  (2, 431)	1
  (2, 336)	1
  (2, 37)	1
  (3, 124)	1
  (3, 352)	2
  (3, 374)	1
  :	:
  (5166, 34)	1
  (5166, 309)	1
  (5167, 207)	1
  (5167, 148)	1
  (5167, 417)	1
  (5167, 186)	1
  (5167, 210)	1
  (5167, 456)	1
  (5167, 32)	1
  (5167, 233)	1
  (5167, 375)	1
  (5167, 146)	1
  (5167, 400)	1
  (5167, 52)	1
  (5167, 284)	1
  (5167, 109)	1
  (5167, 437)	1
  (5167, 70)	1
  (5167, 377)	1
  (5167, 129)	1
  (5167, 172)	1
  (5168, 417)	1
  (5168, 279)	1
  (5168, 211)	2
  (5168, 426)	1

In [87]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    "AI lab teaches deep learning",
    "Deep learning improves AI systems",
    "AI systems use models"
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(X)  # sparse representation
print(X.toarray())  # full dense matrix
print(vectorizer.get_feature_names_out())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14 stored elements and shape (3, 9)>
  Coords	Values
  (0, 0)	1
  (0, 3)	1
  (0, 7)	1
  (0, 1)	1
  (0, 4)	1
  (1, 0)	1
  (1, 1)	1
  (1, 4)	1
  (1, 2)	1
  (1, 6)	1
  (2, 0)	1
  (2, 6)	1
  (2, 8)	1
  (2, 5)	1
[[1 1 0 1 1 0 0 1 0]
 [1 1 1 0 1 0 1 0 0]
 [1 0 0 0 0 1 1 0 1]]
['ai' 'deep' 'improves' 'lab' 'learning' 'models' 'systems' 'teaches'
 'use']

# Splitting Data into Train and Test

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [90]:
x_train.shape

(4135, 500)

In [91]:
x_test.shape

(1034, 500)

In [92]:
y_train.shape

(4135,)

In [93]:
y_test.shape

(1034,)

# Train Model using NaiveBayes

In [94]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB, GaussianNB

In [95]:
model=MultinomialNB()

In [96]:
model.fit(x_train,y_train)

MultinomialNB()

In [97]:
model.score(x_test,y_test)

0.9825918762088974

In [98]:
y_pred=model.predict(x_test)

In [99]:
from sklearn.metrics import confusion_matrix ,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[879   6]
 [ 12 137]]

# Now will check on some text whether show it spam or ham

In [100]:
exmple=["money for scheme laptop buy"]
#example=["I will give you scheme on laptop for government buy it"]
#example=["Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."]

In [101]:
example=cv.transform(exmple)

In [102]:
print(example)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (1, 500)>
  Coords	Values
  (0, 71)	1
  (0, 146)	1
  (0, 270)	1

In [103]:
prediction=model.predict(example)

In [104]:
prediction

array(['ham'], dtype='<U4')